version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8080
      - FLASK_DEBUG=False
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-default_key_for_development_only}
      - LOCAL_DATABASE_PATH=data
    restart: unless-stopped
